
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConversorImplService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/conversor-soap/conversor?wsdl")
public class ConversorImplService
    extends Service
{

    private final static URL CONVERSORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONVERSORIMPLSERVICE_EXCEPTION;
    private final static QName CONVERSORIMPLSERVICE_QNAME = new QName("http://soap/", "ConversorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/conversor-soap/conversor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERSORIMPLSERVICE_WSDL_LOCATION = url;
        CONVERSORIMPLSERVICE_EXCEPTION = e;
    }

    public ConversorImplService() {
        super(__getWsdlLocation(), CONVERSORIMPLSERVICE_QNAME);
    }

    public ConversorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERSORIMPLSERVICE_QNAME, features);
    }

    public ConversorImplService(URL wsdlLocation) {
        super(wsdlLocation, CONVERSORIMPLSERVICE_QNAME);
    }

    public ConversorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERSORIMPLSERVICE_QNAME, features);
    }

    public ConversorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConversorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Conversor
     */
    @WebEndpoint(name = "ConversorImplPort")
    public Conversor getConversorImplPort() {
        return super.getPort(new QName("http://soap/", "ConversorImplPort"), Conversor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Conversor
     */
    @WebEndpoint(name = "ConversorImplPort")
    public Conversor getConversorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "ConversorImplPort"), Conversor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERSORIMPLSERVICE_EXCEPTION!= null) {
            throw CONVERSORIMPLSERVICE_EXCEPTION;
        }
        return CONVERSORIMPLSERVICE_WSDL_LOCATION;
    }

}
