
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Conversor", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Conversor {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws ConversorException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parseInt", targetNamespace = "http://soap/", className = "soap.ParseInt")
    @ResponseWrapper(localName = "parseIntResponse", targetNamespace = "http://soap/", className = "soap.ParseIntResponse")
    @Action(input = "http://soap/Conversor/parseIntRequest", output = "http://soap/Conversor/parseIntResponse", fault = {
        @FaultAction(className = ConversorException.class, value = "http://soap/Conversor/parseInt/Fault/ConversorException")
    })
    public int parseInt(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ConversorException
    ;

}
